ERROR 2013-07-16 22:27:56,111 middleware 9612 140361164859136 Uncaught exception: __init__() got an unexpected keyword argument 'user_data_json_raw'
Traceback (most recent call last):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/jobs/views/jobs.py", line 289, in jobs
    (bridge_headers, search_result, user_data) = serpng.jobs.services.search_master.search(request, query)
  File "/home/oleg/code/web-serpng/code/serpng/../serpng/jobs/services/search_master.py", line 626, in search
    user_data_json_raw=user_data_json)
TypeError: __init__() got an unexpected keyword argument 'user_data_json_raw'
